// Generated by scripts/gen-db-types.mts from the live database schema
// (same shape as `supabase gen types typescript`). Do not edit by hand:
// run `npm run db:types` after applying migrations.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      achievements: {
        Row: {
          category: string
          created_at: string
          date: string
          description: string
          id: number
          organization: string
          pinned: boolean
          title: string
          updated_at: string
        }
        Insert: {
          category: string
          created_at?: string
          date?: string
          description?: string
          id?: never
          organization?: string
          pinned?: boolean
          title: string
          updated_at?: string
        }
        Update: {
          category?: string
          created_at?: string
          date?: string
          description?: string
          id?: never
          organization?: string
          pinned?: boolean
          title?: string
          updated_at?: string
        }
        Relationships: []
      }
      certificates: {
        Row: {
          category: string
          completion_date: string
          created_at: string
          credential_id: string
          description: string
          duration: string
          grade: string
          id: number
          image: string
          issuer: string
          skills: string[]
          title: string
          updated_at: string
          verified: boolean
          verify_url: string
        }
        Insert: {
          category: string
          completion_date?: string
          created_at?: string
          credential_id?: string
          description?: string
          duration?: string
          grade?: string
          id?: never
          image?: string
          issuer: string
          skills?: string[]
          title: string
          updated_at?: string
          verified?: boolean
          verify_url?: string
        }
        Update: {
          category?: string
          completion_date?: string
          created_at?: string
          credential_id?: string
          description?: string
          duration?: string
          grade?: string
          id?: never
          image?: string
          issuer?: string
          skills?: string[]
          title?: string
          updated_at?: string
          verified?: boolean
          verify_url?: string
        }
        Relationships: []
      }
      download_stats: {
        Row: {
          count: number
          day: string
          kind: string
          target_id: string
        }
        Insert: {
          count?: number
          day?: string
          kind: string
          target_id?: string
        }
        Update: {
          count?: number
          day?: string
          kind?: string
          target_id?: string
        }
        Relationships: []
      }
      ebooks: {
        Row: {
          author: string
          category: string
          cover: string
          created_at: string
          description: string
          file_url: string
          id: number
          isbn: string
          pages: number
          subtitle: string
          title: string
          updated_at: string
          year: number | null
        }
        Insert: {
          author?: string
          category?: string
          cover?: string
          created_at?: string
          description?: string
          file_url?: string
          id?: never
          isbn?: string
          pages?: number
          subtitle?: string
          title: string
          updated_at?: string
          year?: number | null
        }
        Update: {
          author?: string
          category?: string
          cover?: string
          created_at?: string
          description?: string
          file_url?: string
          id?: never
          isbn?: string
          pages?: number
          subtitle?: string
          title?: string
          updated_at?: string
          year?: number | null
        }
        Relationships: []
      }
      education: {
        Row: {
          coursework: string[]
          created_at: string
          degree: string
          description: string
          end_date: string
          gpa: string
          id: number
          logo: string
          major: string
          skills: string[]
          sort_order: number
          start_date: string
          status: string
          university: string
          updated_at: string
        }
        Insert: {
          coursework?: string[]
          created_at?: string
          degree: string
          description?: string
          end_date?: string
          gpa?: string
          id?: never
          logo?: string
          major?: string
          skills?: string[]
          sort_order?: number
          start_date?: string
          status?: string
          university: string
          updated_at?: string
        }
        Update: {
          coursework?: string[]
          created_at?: string
          degree?: string
          description?: string
          end_date?: string
          gpa?: string
          id?: never
          logo?: string
          major?: string
          skills?: string[]
          sort_order?: number
          start_date?: string
          status?: string
          university?: string
          updated_at?: string
        }
        Relationships: []
      }
      experiences: {
        Row: {
          achievements: string[]
          company: string
          created_at: string
          description: string
          end_date: string
          id: number
          location: string
          logo: string
          position: string
          responsibilities: string[]
          skills: string[]
          sort_order: number
          start_date: string
          type: string
          updated_at: string
        }
        Insert: {
          achievements?: string[]
          company: string
          created_at?: string
          description?: string
          end_date?: string
          id?: never
          location?: string
          logo?: string
          position: string
          responsibilities?: string[]
          skills?: string[]
          sort_order?: number
          start_date?: string
          type?: string
          updated_at?: string
        }
        Update: {
          achievements?: string[]
          company?: string
          created_at?: string
          description?: string
          end_date?: string
          id?: never
          location?: string
          logo?: string
          position?: string
          responsibilities?: string[]
          skills?: string[]
          sort_order?: number
          start_date?: string
          type?: string
          updated_at?: string
        }
        Relationships: []
      }
      gallery_items: {
        Row: {
          caption: string
          category: string
          created_at: string
          id: number
          image_url: string
          project_link: string
          title: string
          updated_at: string
        }
        Insert: {
          caption?: string
          category: string
          created_at?: string
          id?: never
          image_url: string
          project_link?: string
          title: string
          updated_at?: string
        }
        Update: {
          caption?: string
          category?: string
          created_at?: string
          id?: never
          image_url?: string
          project_link?: string
          title?: string
          updated_at?: string
        }
        Relationships: []
      }
      languages: {
        Row: {
          created_at: string
          flag: string
          id: number
          level: string
          name: string
          proficiency: number
          updated_at: string
        }
        Insert: {
          created_at?: string
          flag?: string
          id?: never
          level?: string
          name: string
          proficiency?: number
          updated_at?: string
        }
        Update: {
          created_at?: string
          flag?: string
          id?: never
          level?: string
          name?: string
          proficiency?: number
          updated_at?: string
        }
        Relationships: []
      }
      media_assets: {
        Row: {
          bucket: string
          created_at: string
          id: number
          mime_type: string
          name: string
          path: string
          size_bytes: number
          type: string
          url: string
        }
        Insert: {
          bucket: string
          created_at?: string
          id?: never
          mime_type: string
          name: string
          path: string
          size_bytes: number
          type: string
          url: string
        }
        Update: {
          bucket?: string
          created_at?: string
          id?: never
          mime_type?: string
          name?: string
          path?: string
          size_bytes?: number
          type?: string
          url?: string
        }
        Relationships: []
      }
      portfolio_categories: {
        Row: {
          color: string
          created_at: string
          description: string
          id: number
          name: string
          slug: string
          sort_order: number
          updated_at: string
        }
        Insert: {
          color?: string
          created_at?: string
          description?: string
          id?: never
          name: string
          slug: string
          sort_order?: number
          updated_at?: string
        }
        Update: {
          color?: string
          created_at?: string
          description?: string
          id?: never
          name?: string
          slug?: string
          sort_order?: number
          updated_at?: string
        }
        Relationships: []
      }
      projects: {
        Row: {
          category_id: number | null
          created_at: string
          description: string
          id: number
          image: string
          link: string
          methodology: string
          objective: string
          problem: string
          results: string
          short_description: string
          status: string
          technologies: string[]
          title: string
          tools: string[]
          updated_at: string
        }
        Insert: {
          category_id?: number | null
          created_at?: string
          description?: string
          id?: never
          image?: string
          link?: string
          methodology?: string
          objective?: string
          problem?: string
          results?: string
          short_description?: string
          status?: string
          technologies?: string[]
          title: string
          tools?: string[]
          updated_at?: string
        }
        Update: {
          category_id?: number | null
          created_at?: string
          description?: string
          id?: never
          image?: string
          link?: string
          methodology?: string
          objective?: string
          problem?: string
          results?: string
          short_description?: string
          status?: string
          technologies?: string[]
          title?: string
          tools?: string[]
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "projects_category_id_fkey"
            columns: ["category_id"]
            isOneToOne: false
            referencedRelation: "portfolio_categories"
            referencedColumns: ["id"]
          },
        ]
      }
      rate_limits: {
        Row: {
          count: number
          key: string
          window_start: string
        }
        Insert: {
          count?: number
          key: string
          window_start?: string
        }
        Update: {
          count?: number
          key?: string
          window_start?: string
        }
        Relationships: []
      }
      research_papers: {
        Row: {
          abstract: string
          area: string
          authors: string[]
          created_at: string
          doi: string
          id: number
          journal: string
          keywords: string[]
          pdf_url: string
          preprint_url: string
          status: string
          submission_date: string | null
          title: string
          updated_at: string
          url: string
          version: string
          year: number | null
        }
        Insert: {
          abstract?: string
          area?: string
          authors?: string[]
          created_at?: string
          doi?: string
          id?: never
          journal?: string
          keywords?: string[]
          pdf_url?: string
          preprint_url?: string
          status: string
          submission_date?: string | null
          title: string
          updated_at?: string
          url?: string
          version?: string
          year?: number | null
        }
        Update: {
          abstract?: string
          area?: string
          authors?: string[]
          created_at?: string
          doi?: string
          id?: never
          journal?: string
          keywords?: string[]
          pdf_url?: string
          preprint_url?: string
          status?: string
          submission_date?: string | null
          title?: string
          updated_at?: string
          url?: string
          version?: string
          year?: number | null
        }
        Relationships: []
      }
      site_settings: {
        Row: {
          key: string
          updated_at: string
          value: Json
        }
        Insert: {
          key: string
          updated_at?: string
          value: Json
        }
        Update: {
          key?: string
          updated_at?: string
          value?: Json
        }
        Relationships: []
      }
      skills: {
        Row: {
          category: string
          created_at: string
          id: number
          level: number
          name: string
          updated_at: string
        }
        Insert: {
          category: string
          created_at?: string
          id?: never
          level: number
          name: string
          updated_at?: string
        }
        Update: {
          category?: string
          created_at?: string
          id?: never
          level?: number
          name?: string
          updated_at?: string
        }
        Relationships: []
      }
      upcoming_research: {
        Row: {
          area: string
          contribution: string
          created_at: string
          expected_year: string
          id: number
          keywords: string[]
          methodology: string
          question: string
          status: string
          title: string
          updated_at: string
        }
        Insert: {
          area?: string
          contribution?: string
          created_at?: string
          expected_year?: string
          id?: never
          keywords?: string[]
          methodology?: string
          question?: string
          status?: string
          title: string
          updated_at?: string
        }
        Update: {
          area?: string
          contribution?: string
          created_at?: string
          expected_year?: string
          id?: never
          keywords?: string[]
          methodology?: string
          question?: string
          status?: string
          title?: string
          updated_at?: string
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      hit_rate_limit: {
        Args: { p_key: string; p_window_seconds: number }
        Returns: number
      }
      increment_download: {
        Args: { p_kind: string; p_target_id?: string }
        Returns: undefined
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type PublicSchema = Database["public"]

export type Tables<T extends keyof PublicSchema["Tables"]> = PublicSchema["Tables"][T]["Row"]
export type TablesInsert<T extends keyof PublicSchema["Tables"]> = PublicSchema["Tables"][T]["Insert"]
export type TablesUpdate<T extends keyof PublicSchema["Tables"]> = PublicSchema["Tables"][T]["Update"]
