/**
 * Supabase CLI helper that reads connection details from .env.
 * (Types are generated by scripts/gen-db-types.mts: `npm run db:types`.)
 *
 *   npm run db:push   # apply supabase/migrations/* to the hosted database
 *
 * Uses NEXT_PUBLIC_SUPABASE_URL (for the project ref) and SUPABASE_DB_PASSWORD.
 * The password is passed to the CLI but never printed.
 */
import { spawnSync } from "node:child_process";

function requireEnv(name: string): string {
  const value = process.env[name]?.trim();
  if (!value) {
    console.error(`Missing ${name} in .env`);
    process.exit(1);
  }
  return value;
}

const projectRef = new URL(requireEnv("NEXT_PUBLIC_SUPABASE_URL")).hostname.split(".")[0];
const command = process.argv[2];

if (command === "push") {
  const password = encodeURIComponent(requireEnv("SUPABASE_DB_PASSWORD"));
  const dbUrl = `postgresql://postgres:${password}@db.${projectRef}.supabase.co:5432/postgres`;
  const result = spawnSync("npx", ["supabase", "db", "push", "--db-url", dbUrl, "--yes"], {
    stdio: ["inherit", "pipe", "pipe"],
    encoding: "utf8",
  });
  // The CLI echoes its arguments; mask the password.
  process.stdout.write((result.stdout ?? "").replaceAll(password, "***"));
  process.stderr.write((result.stderr ?? "").replaceAll(password, "***"));
  process.exit(result.status ?? 1);
} else {
  console.error("Usage: supabase-db.mts push");
  process.exit(1);
}
